# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  config.vm.box_version = "1809.01"
  config.vm.box_check_update = false

  config.vm.provider "virtualbox" do |vb|
     vb.gui = false
     vb.memory = "1024" # aqui se define la memoria que tomara cada vm
  end

  config.vm.provision "file", source: "ansible-vagrant.pub", destination: "/home/vagrant/ansible-vagrant.pub"
  config.vm.provision "shell", inline: <<-SHELL
     sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
     systemctl restart sshd
     cat /home/vagrant/ansible-vagrant.pub >> /home/vagrant/.ssh/authorized_keys
  SHELL

  ## Definimos el ci/cd workstation Gitlab - Ansible
  config.vm.define "gitlab" do |gitlab|
    gitlab.vm.hostname = "gitlab.example.lab"
    gitlab.vm.network "private_network", ip: "192.168.33.20"
    gitlab.vm.provider "virtualbox" do |vb|
      vb.memory = "2048" #Definimos 2Gb para GitLab
    end
    ## Instalamos Gitlab-ce
    gitlab.vm.provision "shell", inline: <<-SHELL
      curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.rpm.sh | sudo bash
      sudo EXTERNAL_URL="http://gitlab.example.lab" yum install -y gitlab-ce
      echo "letsencrypt['enable'] = false" >> /etc/gitlab/gitlab.rb
    SHELL
  end
  ## Definimos los servidores web de cada entorno
  ### DEV
  config.vm.define "devweb" do |devweb|
    devweb.vm.hostname = "devweb.example.lab"
    devweb.vm.network "private_network", ip: "192.168.33.21"
  end
  ### QA
  config.vm.define "qaweb" do |qaweb|
    qaweb.vm.hostname = "qaweb.example.lab"
    qaweb.vm.network "private_network", ip: "192.168.33.22"
  end
  ### PROD
  config.vm.define "web" do |web|
    web.vm.hostname = "web.example.lab"
    web.vm.network "private_network", ip: "192.168.33.23"
  end
  ### GitLab Runner Node 1
  config.vm.define "runner01" do |runner01|
    runner01.vm.hostname = "runner01.example.lab"
    runner01.vm.network "private_network", ip: "192.168.33.24"
    runner01.vm.provision "shell", inline: <<-SHELL
      curl -L https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.rpm.sh | sudo bash
      yum -y install gitlab-runner
      echo "192.168.33.20 gitlab.example.lab gitlab" >> /etc/hosts 
      echo "gitlab-runner ALL=(ALL)       NOPASSWD: ALL" > /etc/sudoers.d/sudo_runner
    SHELL
  end
  

end
